Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, axs = plt.subplots(3,1, sharex = False,
                       figsize = (6,4.5))

sty = {"ec": 'black',
      "zorder": 10}

ax = axs[0]
b = -0.5, 0.5, 9.5, 10.5, 19.5, 20.5, 29.5, 30.5, 215.5, 216.6
ax.hist(incomes, **sty,
       density = True,
       bins = b)

ax = axs[1]
b = -e, 10+e, 20 + e, 30+e,  216-5, 216+5
b = -5, 5, 15, 25, 35, 216-5, 216+5
ax.hist(incomes, **sty,
       density = True,
       bins = b)

ax = axs[2]
b = -e, 10+e, 20 + e, 30+e, 216+5
b = -5, 5, 15, 25, 35, 216+5
ax.hist(incomes, **sty,
       density = True,
       bins = b)

# yticks
axs[0].set_ylim(0, .425)
axs[0].set_yticks([0, .125, .25, .375])
    
axs[1].set_ylim(0, .0425)
axs[1].set_yticks([0, .0125, .025, .0375])
 
axs[2].set_ylim(0, .0425)
axs[2].set_yticks([0, .0125, .025, .0375])
axs[2].set_xlabel("Income ($)")
#axs[3].set_ylim(0, .0425)
#axs[3].set_yticks([0, .0125, .025, .0375])
 
    
for ax in axs:
    ax.set_xticks( [0,10,20,30,216] )
    #ax.set_yticks([0,1,2,3,4,5])
    ax.yaxis.grid(True, zorder = -10)
    y_ticks = ax.get_yticks()
    ax.set_yticks(y_ticks)
    ax.set_yticklabels(['{:.2f}'.format(y*100) for y in y_ticks])
    


axs[0].set_title("Income Histograms")
plt.tight_layout()
plt.savefig("images/income_histograms.svg", format = 'svg', transparent = True)

plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 14[0m
[1;32m      9[0m ax[38;5;241m.[39mhist(incomes, [38;5;241m*[39m[38;5;241m*[39msty,
[1;32m     10[0m        density [38;5;241m=[39m [38;5;28;01mTrue[39;00m,
[1;32m     11[0m        bins [38;5;241m=[39m b)
[1;32m     13[0m ax [38;5;241m=[39m axs[[38;5;241m1[39m]
[0;32m---> 14[0m b [38;5;241m=[39m [38;5;241m-[39m[43me[49m, [38;5;241m10[39m[38;5;241m+[39me, [38;5;241m20[39m [38;5;241m+[39m e, [38;5;241m30[39m[38;5;241m+[39me,  [38;5;241m216[39m[38;5;241m-[39m[38;5;241m5[39m, [38;5;241m216[39m[38;5;241m+[39m[38;5;241m5[39m
[1;32m     15[0m b [38;5;241m=[39m [38;5;241m-[39m[38;5;241m5[39m, [38;5;241m5[39m, [38;5;241m15[39m, [38;5;241m25[39m, [38;5;241m35[39m, [38;5;241m216[39m[38;5;241m-[39m[38;5;241m5[39m, [38;5;241m216[39m[38;5;241m+[39m[38;5;241m5[39m
[1;32m     16[0m ax[38;5;241m.[39mhist(incomes, [38;5;241m*[39m[38;5;241m*[39msty,
[1;32m     17[0m        density [38;5;241m=[39m [38;5;28;01mTrue[39;00m,
[1;32m     18[0m        bins [38;5;241m=[39m b)

[0;31mNameError[0m: name 'e' is not defined

